### ISSUE TITLE
PGP installation is required, but no help on how to find a good guide on installation

### ISSUE THREAD

**Issue by stschmitt** [ibm-cloud-docs/hp-virtual-servers#4]
To perform the steps to setup the environent especially the registration file PGP is needed.
There is no reference in what or how to install PGP. Maybe a pointer to another source would be helpfull

**Comment by priyanayar** [comment]
@stschmitt : Can you please provide further information on when you need this information. Were you performing this task: 
https://cloud.ibm.com/docs/hp-virtual-servers?topic=hp-virtual-servers-imagebuild

**Comment by priyanayar** [comment]
@stschmitt : The topic has been updated with a link, please let me know if this suffices.
