### ISSUE TITLE
Link for further documentation leads to side not available for non IBMers

### ISSUE THREAD

**Issue by stschmitt** [ibm-cloud-docs/hp-virtual-servers#5]
https://cloud.ibm.com/docs/hp-virtual-servers?topic=hp-virtual-servers-byoi#byoi_provision

The link in this section leads to test.cloud.ibm and test.cloud.ibm is not available for customers.

**Comment by priyanayar** [comment]
Fixed this issue. Please verify.

**Comment by priyanayar** [comment]
@stschmitt : Please do verify the link now.

**Comment by stschmitt** [comment]
ok works now
